name: TODO-API-NODE CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  docker-build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t todo-app-test .

      - name: Run Security Audit
        run: docker run --rm todo-app-test npm audit

      - name: Run Linting
        run: docker run --rm todo-app-test npm run lint

      - name: Run Prettier Check
        run: docker run --rm todo-app-test npx prettier --check .

      - name: Run Tests
        run: docker run --rm -e NODE_ENV=test todo-app-test npm test